[uwsgi]

# Application
chdir           = /app/
module          = shop_root.wsgi:application

# TCP socket for inter container communication
socket          = 0.0.0.0:8000

# Process
master          = true

# Clean up
vacuum          = true

