[uwsgi]

# Application
chdir           = /app/
module          = shop_root.wsgi:application

# Unix socket 
socket          = /app/config/uwsgi/shop.soc
chmod-socket    = 666

# Process
master          = true

# Clean up
vacuum          = true

