# Generated by Django 5.1.2 on 2026-06-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bkash_trx_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
