name: Deploy to GCE

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USERNAME }}
          key: ${{ secrets.GCE_SSH_KEY }}
          script: |
            cd ~/ecommerce-server
            git pull origin master
            echo "${{ secrets.ENV_PROD }}" > .env.prod
            sudo chown -R $USER:$USER data/
            sudo chown -R 33:33 media_root
            sudo certbot renew --quiet
            sudo cp /etc/letsencrypt/live/altas.duckdns.org/fullchain.pem ssl/shop.crt
            sudo cp /etc/letsencrypt/live/altas.duckdns.org/privkey.pem ssl/shop.key
            sudo chown -R $USER:$USER ssl/
            docker compose -f docker-compose-prod.yml up -d --build
            docker compose -f docker-compose-prod.yml exec -T web python manage.py migrate
            docker compose -f docker-compose-prod.yml exec -T web python manage.py collectstatic --noinput